[theme]
#red# primaryColor="#F63366"
#darkprimaryColor="blue"
#light??primaryColor="#d9e1f2"
primaryColor="#84A3E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="Inter"
